#!/usr/bin/perl

# created 12Aug2013,RCB & 13Aug2013 Ray St. Onge
# script to input csv into dhcpd.conf

use strict;
# use warnings;
# use File::Slurp;

#change input path as needed
my $inputfile = "/home/tech/dhcpinput.csv";
my $line;

open (my $data , '<',$inputfile) or die("cannot open file");

while ($line = <$data>)
{
  chomp $line;
  #splite line
  my @parseIt = split ",",$line;
  #assign array into variables that make sense
  my $serialNumber = $parseIt[0];
  my $macAddress = $parseIt[1];
  my $address = $parseIt[2];
  my $note = $parseIt[3];
  #strip leading and trailing white space
  $serialNumber =~ s/^\s+|\s+$//g;
  $macAddress =~ s/^\s+|\s+$//g;
  $address =~ s/^\s+|\s+$//g;
  #if there are spaces in the mac address replace them with colons
  $macAddress =~ s/ /:/g;
  #if there are no colon in the mac address, put them in
  if (index($macAddress, ":") == -1) 
  {
    $macAddress =~ s/([0-9a-fA-F]{2})\B/$1:/g;
  } 
  #if remove leading S from serial number
  if (substr($serialNumber,0,1) == "S")
  {
    $serialNumber = substr($serialNumber,1);
  }
  #if there is a note, make sure it has a #
  if (length($note) != 0)
  {
    $note = "#".$note.";";  
  }
print
"host $serialNumber
{
        hardware ethernet $macAddress;
        fixed-address $address;
        $note
}\n";
}
close $data;
