delete from asset;
ALTER TABLE `trackerVS`.`asset` AUTO_INCREMENT = 1 ;
delete from assetToTicket;
ALTER TABLE `trackerVS`.`assetToTicket` AUTO_INCREMENT = 1 ;
delete from attachment;
ALTER TABLE `trackerVS`.`attachment` AUTO_INCREMENT = 1 ;
delete from comment;
ALTER TABLE `trackerVS`.`comment` AUTO_INCREMENT = 1 ;
delete from history;
ALTER TABLE `trackerVS`.`history` AUTO_INCREMENT = 1 ;
delete from monitor;
ALTER TABLE `trackerVS`.`monitor` AUTO_INCREMENT = 1 ;
delete from ticket;
ALTER TABLE `trackerVS`.`ticket` AUTO_INCREMENT = 1 ;
delete from ticketCC;
ALTER TABLE `trackerVS`.`ticketCC` AUTO_INCREMENT = 1 ;
delete from ticketDependencies;
ALTER TABLE `trackerVS`.`ticketDependencies` AUTO_INCREMENT = 1 ;
delete from ticketToAsset;
ALTER TABLE `trackerVS`.`ticketToAsset` AUTO_INCREMENT = 1 ;
delete from ticketToAttachment;
ALTER TABLE `trackerVS`.`ticketToAttachment` AUTO_INCREMENT = 1 ;
delete from ticketToInsurancePayment;
ALTER TABLE `trackerVS`.`ticketToInsurancePayment` AUTO_INCREMENT = 1 ;
delete from ticketToInsuranceRepairComplete;
ALTER TABLE `trackerVS`.`ticketToInsuranceRepairComplete` AUTO_INCREMENT = 1 ;
delete from poNumber;
ALTER TABLE `trackerVS`.`poNumber` AUTO_INCREMENT = 1 ;
delete from contract;
ALTER TABLE `trackerVS`.`contract` AUTO_INCREMENT = 1 ;
